{
	"openapi": "3.0.1",
	"info": {
		"title": "REST API for SmartSense Gaia-X Signer Tool",
		"version": "1.0.0"
	},
	"servers": [{ "url": "http://localhost:8000/" }],
	"paths": {
		"/v1/update-log": {
			"post": {
				"summary": "Update Log Level",
				"description": "Update Log Level of Application",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/LogLevelSchemaBody"
							},
							"examples": {
								"silly": {
									"value": {
										"logLevel": "silly"
									}
								},
								"debug": {
									"value": {
										"logLevel": "debug"
									}
								},
								"warn": {
									"value": {
										"logLevel": "warn"
									}
								},
								"error": {
									"value": {
										"logLevel": "error"
									}
								},
								"info": {
									"value": {
										"logLevel": "info"
									}
								},
								"verbose": {
									"value": {
										"logLevel": "verbose"
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								},
								"examples": {
									"Log Level": {
										"summary": "Update Log Level",
										"value": {
											"message": "Log Updated"
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/create-web-did": {
			"post": {
				"summary": "Create Web DID",
				"description": "Required domain name to create did:web",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/CreateDIDSchemaBody"
							},

							"examples": {
								"Domain": {
									"value": {
										"domain": "dev.smartproof.in"
									}
								},
								"DomainWithX5U": {
									"value": {
										"domain": "dev.smartproof.in",
										"x5u": "https://dev.smartproof.in/.well-known/x509CertificateChain.pem"
									}
								},
								"DomainWithTenant": {
									"value": {
										"domain": "dev.smartproof.in",
										"tenant": "smart"
									}
								},
								"DomainWithService": {
									"value": {
										"domain": "dev.smartproof.in",
										"services": [
											{
												"type": "CredentialRegistry",
												"serviceEndpoint": "https://ssi.eecc.de/api/registry/vcs"
											}
										]
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/verify-web-did": {
			"post": {
				"summary": "Verify Web DID",
				"description": "Required did:web, verification method and private key",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/VerifyDIDSchemaBody"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/get/trust-index": {
			"post": {
				"summary": "Calculation of Trust index, Veracity & Transperency",
				"description": "Calculates Trust index, Veracity & Transperency using holder VC and self description of service offering",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/GetTrustIndexSchemaBody"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								},
								"examples": {
									"trustIndex": {
										"summary": "Trust index, Veracity & Transperency of service offering",
										"value": {
											"message": "Success",
											"data": {
												"veracity": 0.25,
												"transparency": 1.4,
												"trustIndex": 0.825,
												"certificateDetails": {
													"validFrom": "Apr 21 00:00:00 2023 GMT",
													"validTo": "Apr 20 23:59:59 2024 GMT",
													"subject": {
														"jurisdictionCountry": "DE",
														"jurisdictionSate": "Hamburg",
														"jurisdictionLocality": "Hamburg",
														"businessCategory": "Private Organization",
														"serialNumber": "HRB 170364",
														"country": "DE",
														"state": "Hamburg",
														"locality": "Hamburg",
														"organization": "deltaDAO AG",
														"commonName": "www.delta-dao.com"
													},
													"issuer": {
														"commonName": "DigiCert EV RSA CA G2",
														"organization": "DigiCert Inc",
														"country": "US"
													}
												}
											}
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/gaia-x/legal-participant": {
			"post": {
				"summary": "LegalParticipant On GaiaX",
				"description": "LegalParticipant On GaiaX",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/OnBoardGaiaXSchemaBody"
							},
							"examples": {
								"LegalParticipant": {
									"value": {
										"privateKey": "Base64 Encoded -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----",
										"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
										"verificationMethod": "did:web:casio34.smart-x.smartsenselabs.com",
										"vcs": {
											"legalParticipant": {
												"@context": [
													"https://www.w3.org/2018/credentials/v1",
													"https://w3id.org/security/suites/jws-2020/v1",
													"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
												],
												"type": ["VerifiableCredential"],
												"id": "did:web:casio34.smart-x.smartsenselabs.com",
												"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
												"issuanceDate": "2023-07-28T11:13:53.734Z",
												"credentialSubject": {
													"id": "https://casio34.smart-x.smartsenselabs.com/d3ef8323-5a75-4a88-a97b-730deb535405/participant.json#0",
													"type": "gx:LegalParticipant",
													"gx:legalName": "Green World",
													"gx:legalRegistrationNumber": {
														"id": "https://casio34.smart-x.smartsenselabs.com/d3ef8323-5a75-4a88-a97b-730deb535405/participant.json#1"
													},
													"gx:headquarterAddress": {
														"gx:countrySubdivisionCode": "BE-BRU"
													},
													"gx:legalAddress": {
														"gx:countrySubdivisionCode": "BE-BRU"
													},
													"gx:parentOrganization": [{ "id": "https://wizard-api.smart-x.smartsenselabs.com/195f8f7a-e0b9-4105-a94f-911455ff88ac/participant.json#0" }],
													"gx:subOrganization": [{ "id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0" }]
												}
											},
											"legalRegistrationNumber": {
												"@context": ["https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/participant"],
												"type": "gx:legalRegistrationNumber",
												"id": "https://casio34.smart-x.smartsenselabs.com/d3ef8323-5a75-4a88-a97b-730deb535405/participant.json#1",
												"gx:leiCode": "9695007586GCAKPYJ703"
											},
											"gaiaXTermsAndConditions": {
												"@context": [
													"https://www.w3.org/2018/credentials/v1",
													"https://w3id.org/security/suites/jws-2020/v1",
													"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
												],
												"type": ["VerifiableCredential"],
												"issuanceDate": "2023-07-28T11:13:56.533Z",
												"credentialSubject": {
													"@context": "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#",
													"type": "gx:GaiaXTermsAndConditions",
													"gx:termsAndConditions": "The PARTICIPANT signing the Self-Description agrees as follows:\n- to update its descriptions about any changes, be it technical, organizational, or legal - especially but not limited to contractual in regards to the indicated attributes present in the descriptions.\n\nThe keypair used to sign Verifiable Credentials will be revoked where Gaia-X Association becomes aware of any inaccurate statements in regards to the claims which result in a non-compliance with the Trust Framework and policy rules defined in the Policy Rules and Labelling Document (PRLD).",
													"id": "https://casio34.smart-x.smartsenselabs.com/d3ef8323-5a75-4a88-a97b-730deb535405/participant.json#2"
												},
												"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
												"id": "did:web:casio34.smart-x.smartsenselabs.com"
											}
										}
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/gaia-x/service-offering": {
			"post": {
				"summary": "Compline service offering SD",
				"description": "Creates VP for service offering and sends it to compliance service",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/ComplineSOSchemaBody"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								},
								"examples": {
									"serviceOffering": {
										"summary": "Sign Service offering SD from compliance service",
										"value": {
											"data": {
												"completeSD": {
													"selfDescriptionCredential": {
														"@context": "https://www.w3.org/2018/credentials/v1",
														"type": ["VerifiablePresentation"],
														"verifiableCredential": [
															{
																"credentialSubject": {
																	"gx:legalName": "Green World",
																	"gx:headquarterAddress": {
																		"gx:countrySubdivisionCode": "BE-BRU"
																	},
																	"gx:legalAddress": {
																		"gx:countrySubdivisionCode": "BE-BRU"
																	},
																	"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0",
																	"type": "gx:LegalParticipant",
																	"gx:legalRegistrationNumber": {
																		"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#1"
																	}
																},
																"@context": [
																	"https://www.w3.org/2018/credentials/v1",
																	"https://w3id.org/security/suites/jws-2020/v1",
																	"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
																],
																"type": ["VerifiableCredential"],
																"id": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuanceDate": "2023-08-07T16:04:30.307219451Z",
																"proof": {
																	"type": "JsonWebSignature2020",
																	"created": "2023-08-07T10:34:33.838Z",
																	"proofPurpose": "assertionMethod",
																	"verificationMethod": "did:web:casio50.smart-x.smartsenselabs.com",
																	"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..btTzZ3J0O-DcSe8rumxVLBF1jIrHFmonLQ8FWgvrl0ueQGt9VOnRZF5RFN6fHm7Sgx2N4O9EdTFwvV5II-l4nLKK6qHd_f97zNsonL7BRxQ0RB4GpbE6m0pR_XljCzKIQG6RZVyZTAeOdsyWBzGm1M_2hnmTLkBMB33GAJW8fI1d_ou4KbxUfkPiFCfnTUPM3uP5WXGuqC2XqUInL5NJKFZGD6Ld1l6PzPqEGYn-m1UCGQyh6w7l-2NVRT-FHpo3_HHY-xU7RX2F7tDZffCOTbOeiV15xktZWj233BFrcvhBHZ0a14IfifTVFUH0GYmwUPMF1BSS7LCNldFetkcCWQ"
																}
															},
															{
																"@context": ["https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/jws-2020/v1"],
																"type": "VerifiableCredential",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#1",
																"issuer": "did:web:registration.lab.gaia-x.eu:development",
																"issuanceDate": "2023-08-07T10:34:32.101Z",
																"credentialSubject": {
																	"@context": "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#",
																	"type": "gx:legalRegistrationNumber",
																	"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#1",
																	"gx:leiCode": "9695007586GCAKPYJ703",
																	"gx:leiCode-countryCode": "FR"
																},
																"evidence": [
																	{
																		"gx:evidenceURL": "https://api.gleif.org/api/v1/lei-records/",
																		"gx:executionDate": "2023-08-07T10:34:32.101Z",
																		"gx:evidenceOf": "gx:leiCode"
																	}
																],
																"proof": {
																	"type": "JsonWebSignature2020",
																	"created": "2023-08-07T10:34:33.102Z",
																	"proofPurpose": "assertionMethod",
																	"verificationMethod": "did:web:registration.lab.gaia-x.eu:development#X509-JWK2020",
																	"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..Jdx7tQNdCdFc5Gnp1gx8SJ5rqKYAqGXzqEhOJgMnXpmn4MFZvwG97UdnGwgmcqYHsjdqFxEysZDoDnkrmBV-_B1zy2oEcZ9P2I95LS6_H8EfgB6wWdlxyAjg5Hnp-QFoR0N8p6n-hKwEkF1R3e1pVHE2txcTfiGQOfqQGd4EwZAu9Ph6YBdAuYrgBmr4zSEEYNQ5LQRSMvljHSG-h_KHhR4-Fcc-YI_ZUtdPuXbH7IiAo9gAdtPFAW6KDzVKsN1klEzJxp5rVkHYwjsLFCn7wNrYw6u7pbLsSXWRKKypw4gTcdVP6jft4orbLOOWE4gadfkv7AXh8Egk9yIlx_VLBQ"
																}
															},
															{
																"@context": [
																	"https://www.w3.org/2018/credentials/v1",
																	"https://w3id.org/security/suites/jws-2020/v1",
																	"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
																],
																"credentialSubject": {
																	"@Context": [
																		"https://www.w3.org/2018/credentials/v1",
																		"https://w3id.org/security/suites/jws-2020/v1",
																		"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
																	],
																	"gx:termsAndConditions": "The PARTICIPANT signing the Self-Description agrees as follows:\n- to update its descriptions about any changes, be it technical, organizational, or legal - especially but not limited to contractual in regards to the indicated attributes present in the descriptions.\n\nThe keypair used to sign Verifiable Credentials will be revoked where Gaia-X Association becomes aware of any inaccurate statements in regards to the claims which result in a non-compliance with the Trust Framework and policy rules defined in the Policy Rules and Labelling Document (PRLD).",
																	"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#2",
																	"type": "gx:GaiaXTermsAndConditions"
																},
																"id": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuanceDate": "2023-08-07T16:04:30.307219451Z",
																"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
																"type": ["VerifiableCredential"],
																"proof": {
																	"type": "JsonWebSignature2020",
																	"created": "2023-08-07T10:34:34.513Z",
																	"proofPurpose": "assertionMethod",
																	"verificationMethod": "did:web:casio50.smart-x.smartsenselabs.com",
																	"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..SWXsvdPCdnLCnVIkO1cYRca1JMGk0qLVvyW8-cqeHBHn7PbAL0grpW3X0ZyMekncWgJ0-vXBaSdre1OfLSbBXZgpxgqha8OKaCMGqqbSC4IYMmuUeUOvZ_pIAyabFy6OHc45Sm3YT3os7xezF6rl5Kbwn-_nPSZE0izAv269at9Gs_aYUE79UTLyX-_Its4gadRuDdcAhznsrHx4rbNpX9kNh_389zB_lu1lTlt2VqjXBYnbMbknW9-k3lVZZm6giVFxa3fNEAh-1x30-ZdmOs8KNS8mWNl_8SFSE0bmN4BB-3J91bG2aZ8G9GWzu4x3lI-1WmlnEDj5WhaE69Dq0A"
																}
															},
															{
																"type": "VerifiableCredential",
																"id": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuanceDate": "2023-08-10T13:13:12.552192251Z",
																"credentialSubject": {
																	"gx:termsAndConditions": {
																		"gx:URL": "https://aws.amazon.com/service-terms/",
																		"gx:hash": "689be3192f5686526bdddb450463f6c2f752c23b2820a2aae35e6779889e817a"
																	},
																	"gx:policy": ["https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_tc3p_policy.json"],
																	"gx:dataAccountExport": {
																		"gx:requestType": "API",
																		"gx:accessType": "physical",
																		"gx:formatType": "pdf"
																	},
																	"gx:aggregationOf": [
																		{
																			"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_f1b1d420-d44d-439a-8de3-1aeb58f9a493.json"
																		},
																		{
																			"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_19c2bf19-dffe-486e-99bf-bec2301eb061.json"
																		}
																	],
																	"gx:dependsOn": [
																		{
																			"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_xSoK.json"
																		},
																		{
																			"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_Mxt9.json"
																		}
																	],
																	"gx:dataProtectionRegime": "GDPR2016",
																	"type": "gx:ServiceOffering",
																	"gx:providedBy": {
																		"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
																	},
																	"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_tc3p.json"
																},
																"@context": ["https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/jws-2020/v1"],
																"proof": {
																	"type": "JsonWebSignature2020",
																	"created": "2023-08-16T05:48:51.843Z",
																	"proofPurpose": "assertionMethod",
																	"verificationMethod": "did:web:casio50.smart-x.smartsenselabs.com",
																	"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..QDIhZIb-l-wdyZJiiDpJXD0eGJ06w6vrnCCw2ct_fOXD3PwLhnb7YZ0CmfXE0etX9fARFk6bXR9hAF3VAeZo3BJlm9P4gcJ3QeMNKRvPOc643Ta9UA2bU4cRW2aVw1YOs-dVUnbRY0VLE0uhHxIRx-0Ssqnydsin6pbWRIYgR-bI7XcFT3lOzPZAhyU6K3ybbVPJE7hHvm-g49u_r398svdcoAM1Nw5OaPMRmAt73ZP-Z2ygAJR0Jlvsi62higytfuS672jhk0Idyb2PckCV157AVh2GJIFIP2716fX4H7AMzgSYFcJ2oQTq3LrDS18eGJwG5NEH0enkXqS6tPZYCA"
																}
															},
															{
																"type": "VerifiableCredential",
																"id": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuanceDate": "2023-08-08T11:27:35.542Z",
																"credentialSubject": {
																	"gx:termsAndConditions": {
																		"gx:URL": "https://aws.amazon.com/service-terms/",
																		"gx:hash": "689be3192f5686526bdddb450463f6c2f752c23b2820a2aae35e6779889e817a"
																	},
																	"gx:policy": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_xSoK_policy.json",
																	"gx:dataAccountExport": {
																		"gx:requestType": "API",
																		"gx:accessType": "physical",
																		"gx:formatType": "pdf"
																	},
																	"gx:aggregationOf": "https://aws.amazon.com/compliance/?hp=tile&tile=security",
																	"gx:dataProtectionRegime": "GDPR2016",
																	"type": "gx:ServiceOffering",
																	"gx:providedBy": {
																		"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json"
																	},
																	"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_xSoK.json"
																},
																"@context": ["https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/jws-2020/v1"],
																"proof": {
																	"type": "JsonWebSignature2020",
																	"created": "2023-08-08T11:27:39.660Z",
																	"proofPurpose": "assertionMethod",
																	"verificationMethod": "did:web:casio50.smart-x.smartsenselabs.com",
																	"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..NRX1pJRgbrwmA3jnqSkeGX65BpMXK2BnN5bKnWcEN6ir7UgGEZrkDvHlbzwVtbqgb-sKzFsDm2iEbXW9VJHjB6iO-inAMqFeH-lJjKHe9cVMmvFy6enjeuiJrlfvBq7jLE_qU57lAhSMMNFVJ-lJtcnPSCKQuH99Dg1OsY0dnw_jWQEwQZBth25v0BTb9i3UaMQ6qkZuUlQG6Ukm46DnYhy_5ZfzlrcPV9VwqHsJOMem6SWoodhgfKSM_E8AAAM6Cn3VEljAMGb3GsmLE21GzSei7mZ9CIKfLzReygRjJsVXV9Eis1fZkMn5WMf06xSugQRlsnDtPy0YR5oK1TfIWQ"
																}
															},
															{
																"type": "VerifiableCredential",
																"id": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
																"issuanceDate": "2023-08-08T11:29:26.389Z",
																"credentialSubject": {
																	"gx:termsAndConditions": {
																		"gx:URL": "https://aws.amazon.com/service-terms/",
																		"gx:hash": "689be3192f5686526bdddb450463f6c2f752c23b2820a2aae35e6779889e817a"
																	},
																	"gx:policy": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_Mxt9_policy.json",
																	"gx:dataAccountExport": {
																		"gx:requestType": "API",
																		"gx:accessType": "physical",
																		"gx:formatType": "pdf"
																	},
																	"gx:aggregationOf": "https://aws.amazon.com/compliance/?hp=tile&tile=security",
																	"gx:dataProtectionRegime": "GDPR2016",
																	"type": "gx:ServiceOffering",
																	"gx:providedBy": {
																		"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json"
																	},
																	"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_Mxt9.json"
																},
																"@context": ["https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/jws-2020/v1"],
																"proof": {
																	"type": "JsonWebSignature2020",
																	"created": "2023-08-08T11:29:30.054Z",
																	"proofPurpose": "assertionMethod",
																	"verificationMethod": "did:web:casio50.smart-x.smartsenselabs.com",
																	"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..aPp616viJ513iRXLe2rb5Z3uF4RvghlirrijmeMeBLu5ML7xJenPmpvuAP0qQ8xat9cWjWdBqmEOJ2tnUzPP1Qq1k1mDRYU5n42eaxVDEflDP4yrRMsAEYWZkrb-iMCGa6q-ivh0a9GGkOhLmZcHzN8XLZHhPkqz_eZ4PgP3UVlOsNpMIZFf3J_mCVkEhsIDZe03qU6vc7-japiI4NtJzeUlzyHHKhTuaiRCE87ac7_0D1oQPkll6eFY-50peLiFq_2NjPsNCdW1p7rtqoZSDwuy7_TJ7RT1mBlem4AIumtddBNmkcnvZm5zdADnRzRjJBJZI7O4JSylM3Xo0aB6fA"
																}
															}
														]
													},
													"complianceCredential": {
														"@context": [
															"https://www.w3.org/2018/credentials/v1",
															"https://w3id.org/security/suites/jws-2020/v1",
															"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
														],
														"type": ["VerifiableCredential"],
														"id": "https://compliance.lab.gaia-x.eu/development/credential-offers/e541b0ad-df21-424c-bc53-c852c34335c8",
														"issuer": "did:web:compliance.lab.gaia-x.eu:development",
														"issuanceDate": "2023-08-16T05:49:14.916Z",
														"expirationDate": "2023-11-14T05:49:14.916Z",
														"credentialSubject": [
															{
																"type": "gx:compliance",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0",
																"integrity": "sha256-372994ed4b18b7f4252626a48c510aa170cb3a04717d2501ccf1982ed85a9b12",
																"version": "22.10"
															},
															{
																"type": "gx:compliance",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#1",
																"integrity": "sha256-20059a7a182d8a840ee25f8773446aa2f0564c0ff82d359b8a1b194bf1f98045",
																"version": "22.10"
															},
															{
																"type": "gx:compliance",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#2",
																"integrity": "sha256-f897639cb8a0236874ec395a3b0443986fcf5e3b1ac4ac1f3978e72e685dea2f",
																"version": "22.10"
															},
															{
																"type": "gx:compliance",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_tc3p.json",
																"integrity": "sha256-cf43fe00d3fcd9715612accbcfdae5e216a8fd57fa7899ace817a3ec8a099571",
																"version": "22.10"
															},
															{
																"type": "gx:compliance",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_xSoK.json",
																"integrity": "sha256-401e6999d2491a4f2f22df6fbd0105df2fe7e7324e82802e20289be82c4bc72e",
																"version": "22.10"
															},
															{
																"type": "gx:compliance",
																"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_Mxt9.json",
																"integrity": "sha256-70312488f04f1de60e0857a71bbdc899aee59f4615f3193d7ffeaed84af89a65",
																"version": "22.10"
															}
														],
														"proof": {
															"type": "JsonWebSignature2020",
															"created": "2023-08-16T05:49:15.642Z",
															"proofPurpose": "assertionMethod",
															"jws": "eyJhbGciOiJQUzI1NiIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..TPhiSzSBoroPoXBMWBvVZ5FOLemta9EZVsgkfiSRtmSIcUPf34ne-gI6Jk2B6aT2aajNmuNnfYsmLQRF32csGVdZU-6VBcwZIWyFD0sD60AIbXdtmFIlfz1WnB_K6o4KsRbHPyrIF4gzI1eEhEAxcewyQPJfjRMoI7c5LxRwYfgGCnybu4kACp_UNZZDdOZx65eKydZ_td0N2cDUXpFhJsQuDyjY8Nz9dMmXkQK0ow70yWwt3MnxbaKgIkjVSHMgE6n1LNX_KWasjTRb3Ln9leETxQmdSycvkkGJ3aRKlSu36weAji3V3rNbA9AZsBYjwb4EtkA9AeRLpOgE7W-viw",
															"verificationMethod": "did:web:compliance.lab.gaia-x.eu:development#X509-JWK2020"
														}
													}
												},
												"trustIndex": {
													"veracity": 0.25,
													"transparency": 1,
													"trustIndex": 0.625,
													"certificateDetails": {
														"validFrom": "Aug  7 08:16:38 2023 GMT",
														"validTo": "Nov  5 08:16:37 2023 GMT",
														"subject": {
															"jurisdictionCountry": null,
															"jurisdictionSate": null,
															"jurisdictionLocality": null,
															"businessCategory": null,
															"serialNumber": null,
															"country": null,
															"state": null,
															"locality": null,
															"organization": null,
															"commonName": "casio50.smart-x.smartsenselabs.com"
														},
														"issuer": {
															"commonName": "R3",
															"organization": "Let's Encrypt",
															"country": "US"
														}
													}
												}
											},
											"message": "Service offering SD signed successfully"
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/gaia-x/resource": {
			"post": {
				"summary": "Resources On GaiaX",
				"description": "Resources On GaiaX",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/OnBoardGaiaXSchemaBody"
							},
							"examples": {
								"VirtualDataResource": {
									"value": {
										"privateKey": "Base64 Encoded -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----",
										"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
										"verificationMethod": "did:web:casio34.smart-x.smartsenselabs.com",
										"vcs": {
											"resource": {
												"@context": [
													"https://www.w3.org/2018/credentials/v1",
													"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
												],
												"type": ["VerifiableCredential"],
												"id": "did:web:casio34.smart-x.smartsenselabs.com",
												"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
												"issuanceDate": "2023-08-07T16:04:30.307219451Z",
												"credentialSubject": {
													"@context": "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#",
													"id": "https://wizard-api.smart-x.smartsenselabs.com/uuid/test-resource-2.json",
													"type": "gx:VirtualDataResource",
													"gx:name": "Test Resource 2",
													"gx:description": "Test Resource 2 description",
													"gx:aggregationOf": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_f288e078-c580-4cfe-9c25-2013174c4324.json"
														}
													],
													"gx:copyrightOwnedBy": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
														}
													],
													"gx:license": ["http://smartproof.in/.well-known/license"],
													"gx:policy": ["https://example.com"],
													"gx:producedBy": {
														"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
													},
													"gx:exposedThrough": ["https://wizard-api.smart-x.smartsenselabs.com/uuid/test-resource-2"],
													"gx:containsPII": true
												}
											}
										}
									}
								},
								"PhysicalResource": {
									"value": {
										"privateKey": "Base64 Encoded -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----",
										"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
										"verificationMethod": "did:web:casio34.smart-x.smartsenselabs.com",
										"vcs": {
											"resource": {
												"@context": [
													"https://www.w3.org/2018/credentials/v1",
													"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
												],
												"type": ["VerifiableCredential"],
												"id": "did:web:casio50.smart-x.smartsenselabs.com",
												"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
												"issuanceDate": "2023-08-07T16:04:30.307219451Z",
												"credentialSubject": {
													"@context": "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#",
													"id": "https://wizard-api.smart-x.smartsenselabs.com/uuid/test-resource-2.json",
													"type": "gx:PhysicalResource",
													"gx:name": "Test Resource 2",
													"gx:description": "Test Resource 2 description",
													"gx:aggregationOf": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_f288e078-c580-4cfe-9c25-2013174c4324.json"
														}
													],
													"gx:maintainedBy": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
														}
													],
													"gx:ownedBy": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
														}
													],
													"gx:manufacturedBy": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
														}
													],
													"gx:locationAddress": [
														{
															"gx:countryCode": "FR-DE"
														},
														{
															"gx:countryCode": "AA-DE"
														}
													],
													"gx:location": [
														{
															"gx:gps": "35.89421911 139.94637467"
														},
														{
															"gx:gps": "31.89421911 133.94637467"
														}
													]
												}
											}
										}
									}
								},
								"VirtualSoftwareResource": {
									"value": {
										"privateKey": "Base64 Encoded -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----",
										"issuer": "did:web:casio34.smart-x.smartsenselabs.com",
										"verificationMethod": "did:web:casio34.smart-x.smartsenselabs.com",
										"vcs": {
											"resource": {
												"@context": [
													"https://www.w3.org/2018/credentials/v1",
													"https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#"
												],
												"type": ["VerifiableCredential"],
												"id": "did:web:casio50.smart-x.smartsenselabs.com",
												"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
												"issuanceDate": "2023-08-07T16:04:30.307219451Z",
												"credentialSubject": {
													"@context": "https://registry.lab.gaia-x.eu/development/api/trusted-shape-registry/v1/shapes/jsonld/trustframework#",
													"id": "https://wizard-api.smart-x.smartsenselabs.com/uuid/test-resource-2.json",
													"type": "gx:VirtualSoftwareResource",
													"gx:name": "Test Resource 2",
													"gx:description": "Test Resource 2 description",
													"gx:aggregationOf": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_f288e078-c580-4cfe-9c25-2013174c4324.json"
														}
													],
													"gx:copyrightOwnedBy": [
														{
															"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
														}
													],
													"gx:license": ["https://wizard-api.smart-x.smartsenselabs.com/license"],
													"gx:policy": ["https://example.com"]
												}
											}
										}
									}
								}
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		},
		"/v1/gaia-x/verify": {
			"post": {
				"summary": "Verify Gaia-x VC",
				"description": "Validate Gaia-x VC(gx:LegalParticipant,gx:ServiceOffering,gx:VirtualDataResource,gx:PhysicalResource,gx:VirtualSoftwareResource) with allowed polices (integrityCheck,holderSignature,complianceSignature,complianceCheck",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/VerifySchemaBody"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Success",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/SuccessSchemaResponse"
								},
								"examples": {
									"verifyLP": {
										"summary": "Verify",
										"value": {
											"message": "Success",
											"data": {
												"integrityCheck": true,
												"holderSignature": true,
												"complianceSignature": true,
												"complianceCheck": true,
												"valid": true
											}
										}
									}
								}
							}
						}
					},
					"422": {
						"description": "Validation Error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"400": {
						"description": "Bad Request",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					},
					"500": {
						"description": "Internal server error",
						"content": {
							"application/json": {
								"schema": {
									"$ref": "#/components/schemas/ErrorSchemaResponse"
								}
							}
						}
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"SuccessSchemaResponse": {
				"properties": {
					"data": {
						"type": "object"
					},
					"message": {
						"type": "string"
					}
				}
			},
			"ErrorSchemaResponse": {
				"properties": {
					"error": {
						"type": "string"
					},
					"message": {
						"type": "string"
					}
				}
			},
			"CreateDIDSchemaBody": {
				"required": ["domain"],
				"properties": {
					"domain": {
						"type": "string",
						"example": "dev.smartproof.in"
					},
					"tenant": {
						"type": "string",
						"example": "smart"
					},
					"services": {
						"type": "array",
						"items": {
							"type": "object",
							"properties": {
								"type": {
									"type": "string",
									"example": "CredentialRegistry"
								},
								"serviceEndpoint": {
									"type": "string",
									"example": "https://ssi.eecc.de/api/registry/vcs"
								}
							}
						}
					},
					"x5u": {
						"type": "string",
						"example": "https://dev.smartproof.in/.well-known/x509CertificateChain.pem"
					}
				}
			},
			"VerifyDIDSchemaBody": {
				"required": ["did"],
				"properties": {
					"did": {
						"type": "string",
						"example": "did:web:casio34.smart-x.smartsenselabs.com"
					},
					"verificationMethod": {
						"type": "string",
						"example": "did:web:casio34.smart-x.smartsenselabs.com"
					},
					"privateKey": {
						"type": "string",
						"example": "Base64 Encoded -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
					}
				}
			},
			"OnBoardGaiaXSchemaBody": {
				"required": ["domain"],
				"properties": {
					"domain": {
						"type": "string",
						"example": "gaiaxapi.proofsense.in"
					},
					"tenant": {
						"type": "string",
						"example": "Hella"
					},
					"templateId": {
						"type": "string",
						"example": "LegalParticipant"
					},
					"privateKeyUrl": {
						"type": "string",
						"example": "https://example.com"
					},
					"data": {
						"type": "object"
					}
				}
			},
			"GetTrustIndexSchemaBody": {
				"required": ["participantSD", "serviceOfferingSD"],
				"properties": {
					"participantSD": {
						"type": "string",
						"example": "https://www.delta-dao.com/.well-known/participant.json"
					},
					"serviceOfferingSD": {
						"type": "string",
						"example": "https://delta-dao.com/.well-known/serviceGaiaxDLTNetwork.json"
					}
				}
			},
			"ComplineSOSchemaBody": {
				"required": ["privateKey", "issuer", "verificationMethod", "vcs"],
				"properties": {
					"privateKey": {
						"type": "string",
						"example": "Base64 -----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----"
					},
					"issuer": {
						"type": "string",
						"example": "did:web:casio50.smart-x.smartsenselabs.com"
					},
					"verificationMethod": {
						"type": "string",
						"example": "did:web:casio50.smart-x.smartsenselabs.com"
					},
					"vcs": {
						"type": "object",
						"example": {
							"serviceOffering": {
								"type": "VerifiableCredential",
								"id": "did:web:casio50.smart-x.smartsenselabs.com",
								"issuer": "did:web:casio50.smart-x.smartsenselabs.com",
								"issuanceDate": "2023-08-10T13:13:12.552192251Z",
								"credentialSubject": {
									"gx:termsAndConditions": {
										"gx:URL": "https://aws.amazon.com/service-terms/",
										"gx:hash": "689be3192f5686526bdddb450463f6c2f752c23b2820a2aae35e6779889e817a"
									},
									"gx:policy": ["https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_tc3p_policy.json"],
									"gx:dataAccountExport": {
										"gx:requestType": "API",
										"gx:accessType": "physical",
										"gx:formatType": "pdf"
									},
									"gx:aggregationOf": [
										{
											"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_f1b1d420-d44d-439a-8de3-1aeb58f9a493.json"
										},
										{
											"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/resource_19c2bf19-dffe-486e-99bf-bec2301eb061.json"
										}
									],
									"gx:dependsOn": [
										{
											"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_xSoK.json"
										},
										{
											"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_Mxt9.json"
										}
									],
									"gx:dataProtectionRegime": "GDPR2016",
									"type": "gx:ServiceOffering",
									"gx:providedBy": {
										"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/participant.json#0"
									},
									"id": "https://wizard-api.smart-x.smartsenselabs.com/12081064-8878-477e-8092-564a240c69e2/service_tc3p.json"
								},
								"@context": ["https://www.w3.org/2018/credentials/v1", "https://w3id.org/security/suites/jws-2020/v1"]
							}
						}
					}
				}
			},
			"VerifySchemaBody": {
				"required": ["url", "policies"],
				"properties": {
					"url": {
						"type": "string",
						"example": "https://greenworld.proofsense.in/.well-known/participant.json"
					},
					"policies": {
						"type": "array",
						"example": ["integrityCheck", "holderSignature", "complianceSignature", "complianceCheck"]
					}
				}
			},
			"LogLevelSchemaBody": {
				"required": ["logLevel"],
				"properties": {
					"logLevel": {
						"type": "string"
					}
				}
			}
		}
	}
}
